feat: add functionality of review
IvanMartynovLETI/java-filmorate pull request #6
Opened 2023-06-22 11:44 UTC by IvanMartynovLETI

2023-06-23 07:17 UTC, Igzario reviewed
есть пара не существенных замечаний. в основном на сокращение объема кода))

2023-06-23 07:17 UTC, Igzario commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDbStorage.java
> +        if (reviewId == null) {
можно использовать аннотацию @NotNull в контроллере

2023-06-23 07:17 UTC, Igzario commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDbStorage.java
> +            String userWarning = "User with id: " + userId + " doesn't exist.";
String reviewWarning = "Review with id: " + reviewId + " doesn't exist.";
String userWarning = "User with id: " + userId + " doesn't exist.";
можно вынести в константы класса, сделать их final, и не прописывать каждый раз, эти две строчки используются 8раз

2023-06-23 13:33 UTC, GyuzyalSergeychuk requested changes

2023-06-23 13:33 UTC, GyuzyalSergeychuk commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Optional<List<Review>> getReviews(@RequestParam(required = false) Long filmId,
required = false параметр указывает на то что переменная является не обязательной, в нашем случае filmId  является обязательным, в остальных эндпоинтах аналогично

2023-06-23 13:33 UTC, GyuzyalSergeychuk commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDbStorage.java
> +    public ReviewDbStorage(JdbcTemplate jdbcTemplate, Validator validator) {
не обязательно, но в место конструктора можно использовать @RequiredArgsConstructor

2023-06-23 16:47 UTC, IvanMartynovLETI commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDbStorage.java
> +    public ReviewDbStorage(JdbcTemplate jdbcTemplate, Validator validator) {
Согласен, лучше показать свое владение ломбоком, не зря же мы столько времени его изучали. Пофиксил.

2023-06-23 17:10 UTC, IvanMartynovLETI commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Optional<List<Review>> getReviews(@RequestParam(required = false) Long filmId,
Когда я начинал писать методы этого класса, то заранее было неочевидно, какие параметры обязательные, а какие-нет, поэтому закладывался на худший случай. Если конкретно в этом методе убрать требование необязательности, то валятся 85 тестов из 470. Считаю нужным оставить данную аннотацию там, где она есть. У системы должна быть возможность корректной обработки нештатных ситуаций, даже если в тестах этого нет, уж коль скоро это в коде реализовано.

2023-06-23 17:43 UTC, IvanMartynovLETI commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDbStorage.java
> +        if (reviewId == null) {
Я остановился на этом варианте потому, что он позволяет мне выбросить исключение одного типа, но с разными сообщениями, что облегчает жизнь при отладке.

2023-06-23 18:00 UTC, IvanMartynovLETI commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDbStorage.java
> +                count = REVIEWS_COUNT_BY_DEFAULT;
В данном случае это не имеет смысла, поскольку я должен реализовать достаточно сложную функциональность алгоритма, который действует по-разному в зависимости от переданных ему значений filmId и count. Это означает, что в теле метода getReviews мне все равно придется реализовывать проверки условий и значение по умолчанию, переданное из контроллера не упростит алгоритм.

2023-06-23 18:22 UTC, IvanMartynovLETI commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDbStorage.java
> +        if (review.getUserId() <= 0) {
Считаю, что первую проверку нужно оставить, поскольку если в БД запросить запись с айди <=0, то она выбросит исключение, связанное с тем, что она не сможет привести такое значение к типу данных ключа, которое BIGINT. БД в принципе не должна получить запрос со значением ключа <=0, чем и продиктовано введение дополнительной проверки.

2023-06-23 18:31 UTC, Igzario commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDbStorage.java
> +        if (review.getUserId() <= 0) {
принято

2023-06-23 18:32 UTC, Igzario commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDbStorage.java
> +        if (reviewId == null) {
принято, согласен

2023-06-24 04:28 UTC, IvanMartynovLETI commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDbStorage.java
> +            String userWarning = "User with id: " + userId + " doesn't exist.";
Сделать данные строки константными не получится, поскольку они содержат изменяемые части-reviewId и userId. Если же говорить о том, чтобы сделать эти строки переменными класса, то каждую строку, например, userWarning, придется разбивать так: userWarningStart = "User with id: "; userWarningEnd = " doesn't exist", и в исключение передавать их так throw new EntityNotFoundException(userWarningStart + userId + userWarningEnd). Что мы получаем в итоге? С одной стороны, переиспользуемый код в виде переменных класса userWarningStart, userWarningEnd, reviewWarningStart и reviewWarningEnd, то есть получаются 4 новых переменных класса и несколько худшая читаемость кода, поскольку эти 4 переменные находятся в начале класса, а используются много где, и человеку, не знакомому с кодом придется постоянно смотреть на начальные строки класса чтобы понять, а что же в данном конкретном случае передается в исключение. На мой взгляд от этого пострадает читаемость кода, поэтому предлагаю оставить так, как есть.

2023-06-24 18:20 UTC, merged