Add recommendations
IvanMartynovLETI/java-filmorate pull request #7
Opened 2023-06-22 17:16 UTC by GyuzyalSergeychuk

добавлен тест по рекомендации фильмов
добавлен метод по рекомендации фильмов целевому пользователю

2023-06-23 04:06 UTC, OlgaLizunova requested changes
В целом работа очень хорошая, есть несколько небольших замечаний

2023-06-23 04:06 UTC, OlgaLizunova commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +            List<Long> users = jdbcTemplate.queryForList(
Опять использование цикла при запросе к базе данных

2023-06-23 04:06 UTC, OlgaLizunova commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                            "SELECT film_id FROM film_like WHERE user_id = ?", Long.class, userId);
Тот же комментарий

2023-06-23 04:06 UTC, OlgaLizunova commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                Film film = filmDbStorage.getFilmById(idFilm);
В этом цикле вызывается метод, в котором идет обращение к базе данных

2023-06-24 05:35 UTC, OlgaLizunova reviewed
Отличная работа. Один комментарий остался

2023-06-24 05:35 UTC, OlgaLizunova commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        for (Long idFilm : recommendationsFilmsId) {
Тут еще цикл остался. В методе getFilmById идет обращение к базе данных

2023-06-24 22:31 UTC, GyuzyalSergeychuk commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        for (Long idFilm : recommendationsFilmsId) {
fix

2023-06-25 08:01 UTC, OlgaLizunova commented
ок

2023-06-25 08:07 UTC, OlgaLizunova approved these changes
Теперь все Ок)

2023-06-25 08:23 UTC, IvanMartynovLETI approved these changes

2023-06-25 08:39 UTC, merged