Add director
IvanMartynovLETI/java-filmorate pull request #9
Opened 2023-06-22 18:40 UTC by Igzario

2023-06-22 21:12 UTC, GyuzyalSergeychuk requested changes
Хорошая работа, но есть небольшие недочеты которые нужно поправить

2023-06-22 21:12 UTC, GyuzyalSergeychuk commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +            sqlQuery = "SELECT fd.film_id, fd.director_id, d.director_name FROM film_directors AS fd JOIN directors AS d ON fd.director_id=d.director_id WHERE film_id = ?";
тут и в других местах в классе сбилось форматирование строк

2023-06-23 06:43 UTC, Igzario commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public Collection<Director> findAllDirectors() {
Сделано по аналогии с уже имеющимся кодом

2023-06-23 06:44 UTC, Igzario commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> getFilmsWithDirector(@PathVariable(required = false) final Long directorId,
Согласен, но делал по аналогии с уже имеющимся кодом

2023-06-23 06:44 UTC, Igzario commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDbStorage.java
> +        getDirectorById(director.getId());
Нужна, с помощью неё происходит проверка Film, она здесь для этого

2023-06-23 06:46 UTC, Igzario commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +            sqlQuery = "SELECT fd.film_id, fd.director_id, d.director_name FROM film_directors AS fd JOIN directors AS d ON fd.director_id=d.director_id WHERE film_id = ?";
сделано специально) для удобства чтения кода)

2023-06-23 12:59 UTC, GyuzyalSergeychuk commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDbStorage.java
> +        getDirectorById(director.getId());
Результат работы метода на 64 строке должен возвращать объект Director, так как нет присвоения метода ни какой переменой результат метода уходит в никуда и ни на что не влияет в коде

2023-06-23 13:09 UTC, Igzario commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDbStorage.java
> +        getDirectorById(director.getId());
верно, но лучше сделать проверку одной строкой, чем заново писать проверку на наличие в бд? если в бд такого директора нет, на этой строке отработает проверка в методе getDirectorById

2023-06-23 13:39 UTC, GyuzyalSergeychuk requested changes

2023-06-23 13:39 UTC, GyuzyalSergeychuk commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getFilmsWithDirector(@PathVariable(required = false) final Long directorId,
directorId обязательный параметр, без которого не будет работать метод поэтому надо убрать required = false

2023-06-23 13:41 UTC, Igzario commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getFilmsWithDirector(@PathVariable(required = false) final Long directorId,
согласен

2023-06-23 14:26 UTC, GyuzyalSergeychuk approved these changes

2023-06-24 05:23 UTC, IvanMartynovLETI approved these changes

2023-06-24 05:23 UTC, IvanMartynovLETI commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDbStorage.java
> +        Director director;
Я бы добавил вывод отладочного сообщения log.info("Request to database for getting director by id of '{}' obtained.", id);

2023-06-24 05:23 UTC, IvanMartynovLETI commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        List<Film> films = new ArrayList<>();
Я бы добавил log.info("Request to database for list of films with director obtained.");

2023-06-24 09:44 UTC, Igzario commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        List<Film> films = new ArrayList<>();
согласен, поправил

2023-06-24 09:44 UTC, Igzario commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDbStorage.java
> +        Director director;
согласен, поправил

2023-06-24 09:53 UTC, merged